"""Purchase order PDF generation.

Mirrors `billing/pdf.py`'s `InvoicePDFService` shape exactly — same
`_html_to_pdf` WeasyPrint pattern, same currency-formatting helper —
but without any of the fiscal/compliance machinery (no QR codes, no
legal notices, no credit-note handling). This is an internal
procurement document, not a fiscal invoice.

This PDF is generated on demand for in-app preview/download only. It
is NOT attached to the "send to supplier" email — see
`service.py`'s `_send_email` docstring for why (matches how
invoice_sent/budget_sent already behave in this codebase: neither
attaches a PDF either).
"""

from __future__ import annotations

import asyncio
from datetime import date
from decimal import Decimal
from io import BytesIO
from typing import TYPE_CHECKING

from app.core.utils.currency import format_currency as _fmt_currency

if TYPE_CHECKING:
    from app.core.auth.models import Clinic
    from app.modules.contacts.models import Contact

from .models import PurchaseOrder

_LOCALE_BY_LANG = {"es": "es_ES", "en": "en_US"}

_LABELS = {
    "es": {
        "title": "Orden de Compra",
        "po_number": "N.º de orden",
        "order_date": "Fecha de pedido",
        "expected_delivery": "Entrega prevista",
        "status": "Estado",
        "supplier": "Proveedor",
        "description": "Descripción",
        "qty": "Cant.",
        "unit_price": "Precio Unit.",
        "total": "Total",
        "subtotal": "Subtotal",
        "shipping": "Envío",
        "tax": "Impuestos",
        "grand_total": "TOTAL",
        "notes": "Notas",
        "generated_by": "Generado por",
        "status_labels": {
            "draft": "Borrador",
            "sent": "Enviada",
            "confirmed": "Confirmada",
            "partially_received": "Recibida parcialmente",
            "fully_received": "Recibida completa",
            "cancelled": "Cancelada",
        },
    },
    "en": {
        "title": "Purchase Order",
        "po_number": "PO number",
        "order_date": "Order date",
        "expected_delivery": "Expected delivery",
        "status": "Status",
        "supplier": "Supplier",
        "description": "Description",
        "qty": "Qty",
        "unit_price": "Unit Price",
        "total": "Total",
        "subtotal": "Subtotal",
        "shipping": "Shipping",
        "tax": "Tax",
        "grand_total": "TOTAL",
        "notes": "Notes",
        "generated_by": "Generated by",
        "status_labels": {
            "draft": "Draft",
            "sent": "Sent",
            "confirmed": "Confirmed",
            "partially_received": "Partially received",
            "fully_received": "Fully received",
            "cancelled": "Cancelled",
        },
    },
}


class PurchaseOrderPDFService:
    @staticmethod
    async def generate_pdf(
        po: PurchaseOrder,
        supplier: "Contact",
        clinic: "Clinic",
        locale: str = "es",
    ) -> bytes:
        html_content = PurchaseOrderPDFService._generate_html(po, supplier, clinic, locale)
        # WeasyPrint is CPU-bound; offload to a thread (same as billing/pdf.py).
        return await asyncio.to_thread(PurchaseOrderPDFService._html_to_pdf, html_content)

    @staticmethod
    def _generate_html(po: PurchaseOrder, supplier: "Contact", clinic: "Clinic", locale: str) -> str:
        labels = _LABELS.get(locale, _LABELS["es"])
        money_locale = _LOCALE_BY_LANG.get(locale, "es_ES")

        def fmt(amount: Decimal) -> str:
            return _fmt_currency(amount, getattr(clinic, "currency", "TND"), locale=money_locale)

        items_html = ""
        for i, item in enumerate(sorted(po.items, key=lambda x: x.display_order), 1):
            items_html += f"""
            <tr>
                <td class="number">{i}</td>
                <td class="description">{item.description}</td>
                <td class="quantity">{item.quantity_ordered}</td>
                <td class="price">{fmt(item.unit_price)}</td>
                <td class="total">{fmt(item.line_total)}</td>
            </tr>
            """

        status_label = labels["status_labels"].get(po.status, po.status)
        order_date_str = po.order_date.strftime("%d/%m/%Y") if po.order_date else "-"
        expected_str = (
            po.expected_delivery_date.strftime("%d/%m/%Y") if po.expected_delivery_date else "-"
        )

        notes_html = ""
        if po.notes:
            notes_html = f"""
            <div class="notes-section">
                <div class="section-title">{labels["notes"]}</div>
                <div class="notes-content">{po.notes}</div>
            </div>
            """

        return f"""
        <!DOCTYPE html>
        <html lang="{locale}">
        <head>
            <meta charset="UTF-8">
            <title>{labels["title"]} {po.po_number}</title>
            <style>
                body {{ font-family: 'Helvetica', Arial, sans-serif; font-size: 11px; color: #222; margin: 40px; }}
                h1 {{ font-size: 22px; margin-bottom: 4px; }}
                .header {{ display: flex; justify-content: space-between; margin-bottom: 24px; }}
                .info-group {{ margin-bottom: 6px; }}
                .info-label {{ color: #666; font-size: 9px; text-transform: uppercase; }}
                .info-value {{ font-size: 12px; }}
                .status-badge {{ display: inline-block; padding: 2px 10px; border-radius: 10px; background: #eee; font-size: 10px; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
                th {{ text-align: left; border-bottom: 2px solid #333; padding: 6px 4px; font-size: 10px; text-transform: uppercase; }}
                td {{ padding: 6px 4px; border-bottom: 1px solid #ddd; }}
                .quantity, .price, .total, .number {{ text-align: right; }}
                .totals {{ margin-top: 16px; width: 260px; margin-left: auto; }}
                .totals table {{ margin-top: 0; }}
                .totals td {{ border-bottom: none; padding: 3px 4px; }}
                .grand-total {{ font-weight: bold; font-size: 13px; border-top: 2px solid #333; }}
                .notes-section {{ margin-top: 24px; }}
                .section-title {{ font-size: 10px; text-transform: uppercase; color: #666; margin-bottom: 4px; }}
                .footer {{ margin-top: 40px; font-size: 9px; color: #999; text-align: center; }}
            </style>
        </head>
        <body>
            <div class="header">
                <div>
                    <h1>{labels["title"]}</h1>
                    <div class="info-group">
                        <div class="info-label">{labels["po_number"]}</div>
                        <div class="info-value">{po.po_number}</div>
                    </div>
                </div>
                <div>
                    <div class="info-group">
                        <div class="info-label">{labels["order_date"]}</div>
                        <div class="info-value">{order_date_str}</div>
                    </div>
                    <div class="info-group">
                        <div class="info-label">{labels["expected_delivery"]}</div>
                        <div class="info-value">{expected_str}</div>
                    </div>
                    <div class="info-group">
                        <div class="info-label">{labels["status"]}</div>
                        <div class="status-badge">{status_label}</div>
                    </div>
                </div>
            </div>

            <div class="info-group">
                <div class="info-label">{labels["supplier"]}</div>
                <div class="info-value">
                    {supplier.name}
                    {f"<br>{supplier.phone}" if supplier.phone else ""}
                    {f"<br>{supplier.email}" if supplier.email else ""}
                    {f"<br>{supplier.address}" if supplier.address else ""}
                </div>
            </div>

            <table>
                <thead>
                    <tr>
                        <th class="number">#</th>
                        <th class="description">{labels["description"]}</th>
                        <th class="quantity">{labels["qty"]}</th>
                        <th class="price">{labels["unit_price"]}</th>
                        <th class="total">{labels["total"]}</th>
                    </tr>
                </thead>
                <tbody>
                    {items_html}
                </tbody>
            </table>

            <div class="totals">
                <table>
                    <tr><td>{labels["subtotal"]}:</td><td class="total">{fmt(po.subtotal)}</td></tr>
                    <tr><td>{labels["shipping"]}:</td><td class="total">{fmt(po.shipping_cost)}</td></tr>
                    <tr><td>{labels["tax"]}:</td><td class="total">{fmt(po.tax_amount)}</td></tr>
                    <tr class="grand-total"><td>{labels["grand_total"]}:</td><td class="total">{fmt(po.total)}</td></tr>
                </table>
            </div>

            {notes_html}

            <div class="footer">
                {labels["generated_by"]} {clinic.name if clinic else "DentalPin"} | {date.today().strftime("%d/%m/%Y %H:%M")}
            </div>
        </body>
        </html>
        """

    @staticmethod
    def _html_to_pdf(html_content: str) -> bytes:
        """Identical fallback behavior to billing/pdf.py — if WeasyPrint
        isn't installed, return raw HTML bytes rather than failing."""
        try:
            from weasyprint import HTML

            pdf_buffer = BytesIO()
            HTML(string=html_content).write_pdf(pdf_buffer)
            return pdf_buffer.getvalue()
        except ImportError:
            return html_content.encode("utf-8")
