"""Purchase order PDF generation service (WeasyPrint)."""

from __future__ import annotations

import asyncio
from datetime import datetime
from decimal import Decimal
from html import escape
from io import BytesIO
from typing import TYPE_CHECKING

from app.core.pdf_locales import LOCALE_BY_LANG as _LOCALE_BY_LANG
from app.core.utils.currency import format_currency as _fmt_currency

if TYPE_CHECKING:
    from app.core.auth.models import Clinic

_LABELS = {
    "es": {
        "po": "Orden de Compra",
        "draft": "BORRADOR",
        "supplier": "Proveedor",
        "status": "Estado",
        "expected_date": "Fecha prevista",
        "created_at": "Fecha",
        "notes": "Observaciones",
        "item": "Artículo",
        "items": "Artículos",
        "qty_ordered": "Cant. pedida",
        "qty_received": "Cant. recibida",
        "unit_price": "Precio unit.",
        "total": "Total",
        "line_total": "Importe",
        "generated_by": "Generado por",
        "status_label": {
            "draft": "Borrador",
            "sent": "Enviado",
            "confirmed": "Confirmada",
            "received": "Recibida",
            "cancelled": "Cancelada",
        },
    },
    "en": {
        "po": "Purchase Order",
        "draft": "DRAFT",
        "supplier": "Supplier",
        "status": "Status",
        "expected_date": "Expected date",
        "created_at": "Date",
        "notes": "Notes",
        "item": "Item",
        "items": "Items",
        "qty_ordered": "Qty ordered",
        "qty_received": "Qty received",
        "unit_price": "Unit price",
        "total": "Total",
        "line_total": "Amount",
        "generated_by": "Generated by",
        "status_label": {
            "draft": "Draft",
            "sent": "Sent",
            "confirmed": "Confirmed",
            "received": "Received",
            "cancelled": "Cancelled",
        },
    },
    "fr": {
        "po": "Bon de commande",
        "draft": "BROUILLON",
        "supplier": "Fournisseur",
        "status": "Statut",
        "expected_date": "Date prévue",
        "created_at": "Date",
        "notes": "Observations",
        "item": "Article",
        "items": "Articles",
        "qty_ordered": "Qté commandée",
        "qty_received": "Qté reçue",
        "unit_price": "Prix unitaire",
        "total": "Total",
        "line_total": "Montant",
        "generated_by": "Créé par",
        "status_label": {
            "draft": "Brouillon",
            "sent": "Envoyée",
            "confirmed": "Confirmée",
            "received": "Reçue",
            "cancelled": "Annulée",
        },
    },
    "pt": {
        "po": "Nota de encomenda",
        "draft": "RASCUNHO",
        "supplier": "Fornecedor",
        "status": "Estado",
        "expected_date": "Data prevista",
        "created_at": "Data",
        "notes": "Observações",
        "item": "Artigo",
        "items": "Artigos",
        "qty_ordered": "Qtd. encomendada",
        "qty_received": "Qtd. recebida",
        "unit_price": "Preço unitário",
        "total": "Total",
        "line_total": "Montante",
        "generated_by": "Criado por",
        "status_label": {
            "draft": "Rascunho",
            "sent": "Enviada",
            "confirmed": "Confirmada",
            "received": "Recebida",
            "cancelled": "Cancelada",
        },
    },
    "de": {
        "po": "Bestellung",
        "draft": "ENTWURF",
        "supplier": "Lieferant",
        "status": "Status",
        "expected_date": "Liefertermin",
        "created_at": "Datum",
        "notes": "Anmerkungen",
        "item": "Artikel",
        "items": "Artikel",
        "qty_ordered": "Bestellmenge",
        "qty_received": "Erhaltene Menge",
        "unit_price": "Einzelpreis",
        "total": "Gesamt",
        "line_total": "Betrag",
        "generated_by": "Erstellt von",
        "status_label": {
            "draft": "Entwurf",
            "sent": "Gesendet",
            "confirmed": "Bestätigt",
            "received": "Erhalten",
            "cancelled": "Storniert",
        },
    },
    "hu": {
        "po": "Megrendelés",
        "draft": "PISZKOZAT",
        "supplier": "Szállító",
        "status": "Állapot",
        "expected_date": "Várható dátum",
        "created_at": "Dátum",
        "notes": "Megjegyzések",
        "item": "Cikk",
        "items": "Tételek",
        "qty_ordered": "Rendelt mennyiség",
        "qty_received": "Beérkezett mennyiség",
        "unit_price": "Egységár",
        "total": "Összesen",
        "line_total": "Érték",
        "generated_by": "Létrehozta",
        "status_label": {
            "draft": "Piszkozat",
            "sent": "Elküldve",
            "confirmed": "Visszaigazolva",
            "received": "Beérkezett",
            "cancelled": "Törölve",
        },
    },
    "pl": {
        "po": "Zamówienie",
        "draft": "WERSJA ROBOCZA",
        "supplier": "Dostawca",
        "status": "Status",
        "expected_date": "Przewidywana data",
        "created_at": "Data",
        "notes": "Uwagi",
        "item": "Pozycja",
        "items": "Pozycje",
        "qty_ordered": "Ilość zamówiona",
        "qty_received": "Ilość otrzymana",
        "unit_price": "Cena jednostkowa",
        "total": "Razem",
        "line_total": "Wartość",
        "generated_by": "Utworzone przez",
        "status_label": {
            "draft": "Wersja robocza",
            "sent": "Wysłane",
            "confirmed": "Potwierdzone",
            "received": "Otrzymane",
            "cancelled": "Anulowane",
        },
    },
    "it": {
        "po": "Ordine di acquisto",
        "draft": "BOZZA",
        "supplier": "Fornitore",
        "status": "Stato",
        "expected_date": "Data prevista",
        "created_at": "Data",
        "notes": "Note",
        "item": "Articolo",
        "items": "Articoli",
        "qty_ordered": "Qtà ordinata",
        "qty_received": "Qtà ricevuta",
        "unit_price": "Prezzo unitario",
        "total": "Totale",
        "line_total": "Importo",
        "generated_by": "Creato da",
        "status_label": {
            "draft": "Bozza",
            "sent": "Inviato",
            "confirmed": "Confermato",
            "received": "Ricevuto",
            "cancelled": "Annullato",
        },
    },
    "ar": {
        "po": "أمر شراء",
        "draft": "مسودة",
        "supplier": "المورّد",
        "status": "الحالة",
        "expected_date": "التاريخ المتوقع",
        "created_at": "التاريخ",
        "notes": "ملاحظات",
        "item": "الصنف",
        "items": "الأصناف",
        "qty_ordered": "الكمية المطلوبة",
        "qty_received": "الكمية المستلمة",
        "unit_price": "سعر الوحدة",
        "total": "الإجمالي",
        "line_total": "المبلغ",
        "generated_by": "أنشأها",
        "status_label": {
            "draft": "مسودة",
            "sent": "مُرسل",
            "confirmed": "مؤكد",
            "received": "مستلم",
            "cancelled": "ملغي",
        },
    },
    "ta": {
        "po": "கொள்முதல் ஆணை",
        "draft": "வரைவு",
        "supplier": "வழங்குநர்",
        "status": "நிலை",
        "expected_date": "எதிர்பார்க்கும் தேதி",
        "created_at": "தேதி",
        "notes": "குறிப்புகள்",
        "item": "பொருள்",
        "items": "பொருட்கள்",
        "qty_ordered": "ஆர்டர் அளவு",
        "qty_received": "பெறப்பட்ட அளவு",
        "unit_price": "அலகு விலை",
        "total": "மொத்தம்",
        "line_total": "தொகை",
        "generated_by": "உருவாக்கியது",
        "status_label": {
            "draft": "வரைவு",
            "sent": "அனுப்பப்பட்டது",
            "confirmed": "உறுதிசெய்யப்பட்டது",
            "received": "பெறப்பட்டது",
            "cancelled": "ரத்து செய்யப்பட்டது",
        },
    },
}


class PurchaseOrderPDFService:
    """Self-contained WeasyPrint PDF for a purchase order."""

    @staticmethod
    async def generate_pdf(response: dict, clinic: Clinic, locale: str = "es") -> bytes:
        html = PurchaseOrderPDFService._generate_html(response, clinic, locale)
        return await asyncio.to_thread(PurchaseOrderPDFService._html_to_pdf, html)

    @staticmethod
    def _generate_html(response: dict, clinic: Clinic, locale: str) -> str:
        labels = _LABELS.get(locale, _LABELS["es"])
        # Arabic mirrors the document; every other host locale is LTR (#485).
        rtl_attr = ' dir="rtl"' if locale == "ar" else ""
        status_label = labels["status_label"].get(response["status"], response["status"])
        currency = clinic.currency if clinic else "EUR"
        # One map for every PDF (#441): a German order printed 1,234.56
        # while its invoice printed 1.234,56 (#485).
        money_locale = _LOCALE_BY_LANG.get(locale, "es_ES")

        def money(amount: Decimal) -> str:
            return _fmt_currency(amount, currency, locale=money_locale)

        rows = ""
        grand_total = Decimal("0")
        for idx, line in enumerate(response["lines"], 1):
            line_total = (line["unit_price"] or Decimal("0")) * line["quantity_ordered"]
            grand_total += line_total
            rows += f"""
                <tr>
                    <td class="number">{idx}</td>
                    <td>{escape(line["item_name"])}</td>
                    <td class="qty">{line["quantity_ordered"]}</td>
                    <td class="qty">{line["quantity_received"]}</td>
                    <td class="price">{money(line["unit_price"] or Decimal("0"))}</td>
                    <td class="price">{money(line_total)}</td>
                </tr>
            """

        expected = (
            response["expected_date"].strftime("%d/%m/%Y") if response["expected_date"] else "—"
        )
        created = response["created_at"].strftime("%d/%m/%Y")

        watermark = ""
        if response["status"] == "draft":
            watermark = f'<div class="watermark">{labels["draft"]}</div>'

        note_block = (
            f'<div class="notes-section"><div class="section-title">{labels["notes"]}</div>'
            f'<div class="notes-content">{escape(response["notes"])}</div></div>'
            if response.get("notes")
            else ""
        )

        return f"""<!DOCTYPE html>
        <html lang="{locale}"{rtl_attr}>
        <head>
        <meta charset="UTF-8">
        <style>
            * {{ margin: 0; padding: 0; box-sizing: border-box; }}
            body {{
                font-family: 'Helvetica Neue', Arial, sans-serif;
                font-size: 11pt; line-height: 1.4; color: #333; padding: 20mm;
            }}
            .watermark {{
                position: fixed; top: 50%; left: 50%;
                transform: translate(-50%, -50%) rotate(-45deg);
                font-size: 120px; color: rgba(200, 200, 200, 0.3); z-index: 1000;
            }}
            .header {{
                display: flex; justify-content: space-between;
                margin-bottom: 30px; padding-bottom: 20px;
                border-bottom: 2px solid #2563eb;
            }}
            .clinic-name {{ font-size: 18pt; font-weight: bold; color: #1e40af; margin-bottom: 5px; }}
            .clinic-details {{ font-size: 9pt; color: #666; }}
            .po-info {{ text-align: end; }}
            .po-number {{ font-size: 14pt; font-weight: bold; color: #1e40af; }}
            .po-meta {{ font-size: 9pt; color: #666; margin-top: 5px; }}
            .status-badge {{
                display: inline-block; padding: 3px 10px; border-radius: 12px;
                font-size: 9pt; font-weight: bold; text-transform: uppercase; margin-top: 8px;
            }}
            .status-draft {{ background: #e5e7eb; color: #374151; }}
            .status-sent {{ background: #dbeafe; color: #1e40af; }}
            .status-confirmed {{ background: #fef3c7; color: #92400e; }}
            .status-received {{ background: #d1fae5; color: #065f46; }}
            .status-cancelled {{ background: #fee2e2; color: #991b1b; }}
            .section {{ margin-bottom: 25px; }}
            .section-title {{
                font-size: 11pt; font-weight: bold; color: #1e40af;
                margin-bottom: 10px; padding-bottom: 5px; border-bottom: 1px solid #e5e7eb;
            }}
            table {{ width: 100%; border-collapse: collapse; }}
            th {{
                /* Logical, not physical: a physical ``left`` puts the header
               at the far edge of a wide column when the document is
               right-to-left (#485). */
                background: #f3f4f6; padding: 10px 8px; text-align: start;
                font-size: 9pt; font-weight: 600; color: #374151;
                border-bottom: 2px solid #e5e7eb;
            }}
            td {{ padding: 10px 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }}
            .number {{ width: 30px; text-align: center; }}
            .qty {{ width: 70px; text-align: center; }}
            .price {{ width: 110px; text-align: end; }}
            .totals {{ float: right; width: 300px; margin-top: 20px; }}
            .totals td {{ border-bottom: none; padding: 6px 8px; }}
            .totals .label {{ text-align: start; color: #666; }}
            .totals .value {{ text-align: end; font-weight: 500; }}
            .totals .grand-total {{ font-size: 13pt; font-weight: bold; color: #1e40af; }}
            .notes-section {{ clear: both; padding-top: 20px; margin-top: 20px; }}
            .notes-content {{
                background: #f9fafb; padding: 15px; border-radius: 8px;
                font-size: 10pt; color: #4b5563;
            }}
            .supplier {{ margin-bottom: 15px; }}
            .info-label {{ font-size: 9pt; color: #666; margin-bottom: 2px; }}
            .info-value {{ font-weight: 500; }}
        </style>
        </head>
        <body>
            {watermark}
            <div class="header">
                <div class="clinic-info">
                    <div class="clinic-name">{escape(clinic.name) if clinic else "Dental Clinic"}</div>
                    <div class="clinic-details">{escape(clinic.phone or "")}</div>
                </div>
                <div class="po-info">
                    <div class="po-number">{labels["po"]} {str(response["id"])[:8].upper()}</div>
                    <div class="po-meta">
                        {labels["created_at"]}: {created}
                    </div>
                    <span class="status-badge status-{response["status"]}">{status_label}</span>
                </div>
            </div>

            <div class="section">
                <div class="section-title">{labels["supplier"]}</div>
                <div class="supplier">
                    <div class="info-value">{escape(response["supplier_name"])}</div>
                    <div class="info-label">{labels["expected_date"]}</div>
                    <div class="info-value">{expected}</div>
                </div>
            </div>

            <div class="section">
                <div class="section-title">{labels["items"]}</div>
                <table>
                    <thead>
                        <tr>
                            <th class="number">#</th>
                            <th>{labels["item"]}</th>
                            <th class="qty">{labels["qty_ordered"]}</th>
                            <th class="qty">{labels["qty_received"]}</th>
                            <th class="price">{labels["unit_price"]}</th>
                            <th class="price">{labels["line_total"]}</th>
                        </tr>
                    </thead>
                    <tbody>{rows}</tbody>
                </table>
                <div class="totals">
                    <table>
                        <tr><td class="label">{labels["total"]}:</td><td class="value grand-total">{money(grand_total)}</td></tr>
                    </table>
                </div>
            </div>

            {note_block}

            <div style="clear: both; padding-top: 30px;"></div>
            <div style="font-size: 8pt; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 10px;">
                {labels["generated_by"]} DentalPin | {datetime.now().strftime("%d/%m/%Y %H:%M")}
            </div>
        </body>
        </html>"""

    @staticmethod
    def _html_to_pdf(html_content: str) -> bytes:
        try:
            from weasyprint import HTML

            pdf_buffer = BytesIO()
            HTML(string=html_content).write_pdf(pdf_buffer)
            return pdf_buffer.getvalue()
        except ImportError:
            return html_content.encode("utf-8")
